dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
before_script:
  - truffle version
script:
  - cd node_modules
  - rm -rf republic-sol
  - git clone https://github.com/republicprotocol/republic-sol.git
  - cd republic-sol
  - git checkout 56dafc8c8aad5136681da01cccc88ec9d0189bc2
  - cd ../../
  - npm run coverage
  - cat coverage/lcov.info | ./node_modules/.bin/coveralls
